version: '3.9'
services:
  soketi:
    container_name: 'soketi_server'
    restart: unless-stopped
    image: 'quay.io/soketi/soketi:0.17-16-alpine'
    ports:
      - '6001:6001'
      - '9601:9601'
    environment:
      DEBUG: 1
      DEFAULT_APP_ID: 7007007
      DEFAULT_APP_KEY: event-sub-key
      DEFAULT_APP_SECRET: b854838fe9e1edd5874457cc48bbaf39
    networks:
      - soketi_network

networks:
  soketi_network:
    driver: bridge
